cURL vhost.template

diff --git a/commands/host/ibexa-setup b/commands/host/ibexa-setup
--- a/commands/host/ibexa-setup
+++ b/commands/host/ibexa-setup
@@ -105,7 +105,15 @@ echo "DATABASE_COLLATION=${DB_COLLATION}" >> .env.local
 echo "👷 Saved database details in .env.local"
 
 if [[ "$HTTP_SERVER" == "apache-fpm" ]]; then
-    cp .ddev/ibexa-resources/apache2/vhost.template .ddev/apache/apache-site.conf
+    if ! curl -fsSL \
+        "https://raw.githubusercontent.com/ibexa/post-install/$PRODUCT_BRANCH/resources/templates/apache2/vhost.template" \
+        -o .ddev/apache/apache-site.conf; then
+        echo "⛔️ Could not download template, using local fallback"
+        cp .ddev/ibexa-resources/apache2/vhost.template .ddev/apache/apache-site.conf
+    else
+        echo "👷 Downloaded vhost.template from https://raw.githubusercontent.com/ibexa/post-install/"
+    fi
+
     sed -i "s/%HOST_NAME%/$DDEV_PROJECT.ddev.site/" .ddev/apache/apache-site.conf
     sed -i 's/%HOST_ALIAS%/*.ddev.site/' .ddev/apache/apache-site.conf
     sed -i 's/%IP_ADDRESS%/*/' .ddev/apache/apache-site.conf
